### PR TITLE
usdf_mem.c: add fi_enosys.h

### PR DESCRIPTION
**Pull request by jsquyres**
Fix one usdf issue in prov/usnic/src/usdf_mem.c -- include fi_enosys.h.

### CODE REVIEW

**Comment by jsquyres** [comment]
Sorry; should have mentioned that this is for ofiwg/libfabric#739.

**Comment by bturrubiates** [comment]
Oh did my change break the usnic build? My bad, I just realized that's the only provider I can't test the build for.

**Comment by jsquyres** [comment]
I just pushed another commit here.

Yeah, you broke the usnic build -- no worries; that's what PRs / reviews are for.  :-)

FWIW, you _can_ test the usnic build on Linux; just install libnl (either libnl1 or libnl3; doesn't matter which), and ensure you have the dev headers, too.

**Comment by jsquyres** [comment]
Is the Travis CI failure a false failure?

**Comment by bturrubiates** [comment]
Thanks for the info, where can I get the dev headers? I'll add them to my dev machine.

**Comment by bturrubiates** [comment]
@jsquyres Yeah, ignore that. I need to fix it...

**Comment by bturrubiates** [comment]
Oh the issue is that my travis.yml file is only on my master branch so it's using some sort of default.

**Pull request merged**
